name: Daily Summary Report

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
       - name: Test GitHub Action on a separate branch
         if: github.ref == 'refs/heads/test-branch'
         uses: actions/checkout@v2
         with:
           ref: 'test-branch'
       - name: Authenticate using GitHub Token
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       - name: Fetch Data
         run: python fetch_data.py
         env:
           GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
       - name: Generate Report
         run: python generate_report.py
         env:
           DATA_PATH: ./data/output.json