name: Daily Summary Report

on:
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC every day

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  fetch_repo_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Fetch repository data
        uses: actions/github-script@v5
        with:
          script: |
            const { data: commits } = await github.rest.repos.listCommits({ owner: context.repo.owner, repo: context.repo.repo });
            const commitMessages = commits.map(commit => commit.commit.message);
            const commitAuthors = commits.map(commit => commit.commit.author.name);
            const { data: issues } = await github.rest.issues.listForRepo({ owner: context.repo.owner, repo: context.repo.repo, state: 'all' });
            const openIssues = issues.filter(issue => issue.state === 'open').length;
            const closedIssues = issues.filter(issue => issue.state === 'closed').length;
            core.setOutput('commitMessages', commitMessages);
            core.setOutput('commitAuthors', commitAuthors);
            core.setOutput('openIssues', openIssues);
            core.setOutput('closedIssues', closedIssues);
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate report
        run: |
          echo "## Daily Summary Report" > report.md
          echo "**Date:** $(date '+%Y-%m-%d')" >> report.md
          echo "**Number of Commits:** ${{ steps.fetch_repository_data.outputs.commitMessages | length }}" >> report.md
          echo "**Commit Messages:**" >> report.md
          for msg in ${{ join(fromJson(steps.fetch_repository_data.outputs.commitMessages), '\\n') }}; do
            echo "- $msg" >> report.md
          done
          echo "**Authors:**" >> report.md
          for author in ${{ join(fromJson(steps.fetch_repository_data.outputs.commitAuthors), '\\n') }}; do
            echo "- $author" >> report.md
          done
          echo "**Open Issues:** ${{ steps.fetch_repository_data.outputs.openIssues }}" >> report.md
          echo "**Closed Issues:** ${{ steps.fetch_repository_data.outputs.closedIssues }}" >> report.md
        # Add the actual steps for generating and distributing the report as needed
   save_report:
     needs: generate-report
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
       - name: Save report to 'daily_summary.md'
         run: |
           mv report.md daily_summary.md
       - name: Commit and push report
         uses: actions/github-script@v5
         with:
           script: |
             const fs = require('fs');
             const path = './daily_summary.md';
             const github = require('@actions/github');
             const core = require('@actions/core');
             const exec = require('@actions/exec');
             async function run() {
               const message = 'chore: Update daily summary report';
               const email = 'github-actions[bot]@users.noreply.github.com';
               const name = 'github-actions[bot]';
               const branch = 'main';
               await exec.exec('git', ['config', '--local', 'user.email', email]);
               await exec.exec('git', ['config', '--local', 'user.name', name]);
               await exec.exec('git', ['add', path]);
               await exec.exec('git', ['commit', '-m', message, '--allow-empty']);
               await exec.exec('git', ['push']);
             }
             run();